### ISSUE TITLE
Wrong message type for MQTT Listener:  MQTT instead of MQTT_MESSAGE

### ISSUE THREAD

**Issue by shbatm** [Odianosen25/Monitor-App#1]
Hello! I am trying to implement your new script in ADv4, but I'm struggling to get it running as posted. 

Specifically, I wasn't getting any feedback from the MQTT service (publish was working fine, the subscription wasn't receiving any events).  Changing the [following line](https://github.com/Odianosen25/Monitor-App/blob/33a4ca0519c232715c3e965059713675c9f90a3d/home_presence_app.py#L63):
```python
        self.mqtt.listen_event(self.presence_message, 'MQTT', wildcard = '{}/#'.format(self.presence_topic))
```
to this:
```python
        self.mqtt.listen_event(self.presence_message, 'MQTT_MESSAGE', wildcard = '{}/#'.format(self.presence_topic))
```
seems to solve the issue.

**Comment by Odianosen25** [comment]
Hello @shbatm,

First I am so sorry I am just responding. I don't get any notification in my mail, and just stumbled unto the fact you commented all these while. This is my first comment to a code I have released, to I very much appreciate the fact you using it, and wanting to make it better.

Now to your PR I didn't use "MQTT_MESSAGE" as I do change my `event_name` in the setup, but will respond in the PR
