### ISSUE TITLE
HACS upgrade clobbers home_presence_app.yaml

### ISSUE THREAD

**Issue by alandtse** [Odianosen25/Monitor-App#25]
Update using HACS will destroy the existing home_presence_app.yaml. It probably makes sense to take it out of the repo and add in a home_presence_app.yaml.template. This is because HACs will just recreate the directory.

**Comment by Odianosen25** [comment]
Hello @alandtse,

Ok will do that. Thanks for the update.

Regards

**Comment by Odianosen25** [comment]
This is fixed now, do reopen if not
