### ISSUE TITLE
Documentation and Application discrepancies

### ISSUE THREAD

**Issue by andyinno** [Odianosen25/Monitor-App#3]
Hi!

I just installed AD4 on a pi3 that connects to another pi3 where it is installed Hass.io

I can connect and I see that motion is triggered.

so the 3 way communication is working as expected.

During the setup I set the two plugins for AD4 mqtt and hass and I set mqtt a namespace "mqtt"

during the startup of the app I see in the logs:

    Entity monitor.monitor_state not found in namespace mqtt
    Entity monitor.monitor_state created in namespace: mqtt

from the README file I was expecting to be able to find a monitor entity in home assistant but this entity is not present, or at least I cannot see it from the lovelace add entity menu, either in the entity registry.

- Am I doing something wrong?
- Am I missing something from the README file?

thank you in advance
Andrea

**Comment by Odianosen25** [comment]
Hello @andyinno,

First I am sorry I am just responding. I didn't get any notification for the message.

No you are not doing anything wrong. The `monitor.monitor_state` is only used for AD's internals and nothing more. It has no connection to HASS in anyway.

Hope this helps

Regards

**Comment by Odianosen25** [comment]
Closing this, do reopen if any other thing
