### ISSUE TITLE
Double check away state for BEACON

### ISSUE THREAD

**Issue by nortuzar** [Odianosen25/Monitor-App#36]
This is a follow from my post on the [home assistant forum](https://community.home-assistant.io/t/home-monitor-presence-app-v2/173738/31?u=servido)
I’m having problems with the xiaomi mi band 3 beacons. Standing in the same place, suddenly the confidence drops to 0 and then jump to 100.
https://imgur.com/iwEPbA0

I arrived at 2:00pm to my home and I have been sited in the computer until now (like 2 meters away), and it keep changing from 0 to 100 on confidence
image

Is there a way to add like a recheck on the away status? Like:

- Monitor check and now confidence goes to 0, can it wait 10 seconds and do a recheck to confirm that confidence is 0 and then change to the away status?

Thanks for the great app and the help

**Comment by Odianosen25** [comment]
@nortuzar ,

Hello thanks for this. If possible can you download the use the present dev version and see if it solves your issue? 

Do let me know how it goes.

Regards

**Comment by nortuzar** [comment]
@Odianosen25 , I already try the dev branch. I think it work better but its seems that this is something with the band, maybe at night without activity there is some battery saver mode.

In the link (sorry couldn't paste the screenshot), you can see that I was able to have stable status (home/away), but in the bottom graph there are this drops in confidence from 100 to 0, but I check and its max 1 minute in 0 confidence, then it jumps immediately to 100.
https://imgur.com/a/Vh8tBt1

To avoid problems of false away, I changed the parameters to wait more time before changing to away. I can deal waiting more time to have correct status 
`depart_check_time: 60`
`not_home_timeout: 90`

Thats it, I think you can push this commit to the master branch.

Thanks for the help!
