### ISSUE TITLE
why is it not possible to find Monitor-App in HACS catalogue?!

### ISSUE THREAD

**Issue by northpower25** [Odianosen25/Monitor-App#42]
I don't find the Monitor-App in HACS and manual add the repository failed.

**Comment by Odianosen25** [comment]
Hello @northpower25,

Check under AppDaemon app in HACS default, it should be there. I actually don’t use HACS myself, so honestly not sure what to expect 😬.

Regards

**Comment by Odianosen25** [comment]
I will be closing this, do re-open if still not fixed yet
