### ISSUE TITLE
Documentation typo: "someone_is_home" should be "somebody_is_home"

### ISSUE THREAD

**Issue by donkawechico** [Odianosen25/Monitor-App#46]
README lists incorrect `someone_is_home` option in 3 places:

1. [App Configuration Section](https://github.com/Odianosen25/Monitor-App#app-configuration), in the "key" column.
2. [App Configuration Section](https://github.com/Odianosen25/Monitor-App#app-configuration), in the "default" column. 
3. [Features Section](https://github.com/Odianosen25/Monitor-App#features): `The name of the sensors for everyone_home, everyone_not_home and someone_is_home can be modified to use other names as required. - contributed by shbatm`

This can lead folks to look for a `binary_sensor.someone_is_home` sensor in HASS rather than the correct `binary_sensor.somebody_is_home` sensor.

**Comment by Odianosen25** [comment]
Thanks @donkawechico I have fixed the docs. It was actually supposed to be `someone` and not `somebody`. But if I change the code now, will be a breaking change, so will just leave it as `somebody`.

Thanks and regards
