### ISSUE TITLE
Add support for "cover" gateway sensor

### ISSUE THREAD

**Issue by skynet01** [Odianosen25/Monitor-App#49]
If the garage is hooked up to home assistant usually it shows as [cover](https://www.home-assistant.io/integrations/cover/)  The states are open, opening, closing, closed. Yes I know I can set up another template sensor that converts that to a binary sensor but would be nice if it was supported out of the box :)

Thank you!

**Comment by Odianosen25** [comment]
Hello @skynet01,

Ok this is easy, I guess this is how I will play it, when the entity given for gateway uses a `cover` domain, instead of `on` and `off`, will use `open`and `closed` to run. Makes sense right?

**Comment by skynet01** [comment]
Yes that's correct, you can make it more universal that for any entity someone adds you always check for any of these reported states for true: (y|yes|true|on|home|open)  and the opposite for no states.

**Comment by skynet01** [comment]
just thought of something, you can also add "locked / unlocked" to the list so people can add their locks

**Comment by Odianosen25** [comment]
You can try the dev now, this has been fixed. Re-open if any issues @skynet01

**Comment by skynet01** [comment]
Seems to be working, thanks for making the fix so quickly!  :)

**Comment by Odianosen25** [comment]
Was straight forward. You welcome
