### ISSUE TITLE
Not removing known mac-address

### ISSUE THREAD

**Issue by pointlevel** [Odianosen25/Monitor-App#55]
Hi!

Really great work on this App, thanks. 

I found out that adding new mac's from the App is working properly distributing it out to the nodes, but not removing them from nodes when removing from within the app. Is that by design?

**Comment by Odianosen25** [comment]
@pointlevel,

Yeah removal is planed for after the next release, which should be within the next few days.

Regards

**Comment by Odianosen25** [comment]
Ok  @pointlevel, 

I figured it was actually a relatively straight forward fix, and so been added. Was also requested by @skynet01.

Do try out the present dev, and let me know if it works.

Regards

**Comment by Odianosen25** [comment]
As follow-up to what I wrote, figured it was not as straight forward, so ensure you have the latest dev during tests.

Regards

**Comment by pointlevel** [comment]
It works for me! Thanks!

**Comment by Odianosen25** [comment]
Glad it does, closing now
