### ISSUE TITLE
Add to HACS for easy installation

### ISSUE THREAD

**Issue by codeclinic** [Odianosen25/Monitor-App#6]
Could you possibly add this to HACS? It'd give the project a lot more visibility plus make it so much easier to install and keep updated.

**Comment by Odianosen25** [comment]
Hello @codeclinic, ok I will look into it. I need to first get some PRs done, but haven’t had time to do it yet. Then I work on that.

Regards

**Comment by alandtse** [comment]
Here's the [developer docs](https://hacs.xyz/docs/publish/appdaemon) to help encourage you.

**Comment by Odianosen25** [comment]
@alandtse,

Thanks and as you noticed we already working on it. We are almost complete with everything, and should hopefully be available later next week.

Kind regards

**Comment by Odianosen25** [comment]
Ok this has been done, thanks guys

**Comment by giacomotontini** [comment]
I can't add this repo to HACS. 
```Exception: HacsException
Message: Repostitory structure for master is not compliant
Could not add this repository, make sure it is compliant with HACS.```

What's wrong?
