### ISSUE TITLE
How/Where ot install this.

### ISSUE THREAD

**Issue by codeclinic** [Odianosen25/Monitor-App#7]
Hi,

I successfully installed appdaemon and would love to get your app up and running. however, I don't seem to be able to find anywhere that shows where to place the files for an app. If you could let me know where I need to copy the files to for Monitor-App i'd really appreciate it. 

Thanks.

**Comment by Odianosen25** [comment]
Hello,

Just place it in your apps directory for apps in appdaemon. It should be automatically picked up. 

Regards

**Comment by codeclinic** [comment]
> Hello,
> 
> Just place it in your apps directory for apps in appdaemon. It should be automatically picked up.
> 
I just don't know where that is. Is it created by default or do I need to create it. At present all I can find is an empty appdaemon dir.

**Comment by Odianosen25** [comment]
Hello @codeclinic,

It seems you having issues setting up appdaemon, which is not about this app. Might be better to ask about setting up AD in the AD discord server [here](https://discord.gg/).

But in all it depends on your platform. If you using Hass.io, then I am not so experienced with that unfortunately.

Regards

**Comment by codeclinic** [comment]
I appreciate that, I was just trying to ascertain where the app folder resided and whether it was created by default. I'm assuming from your response that the app folder should be created by default.

**Comment by Odianosen25** [comment]
Yes it should be created by default
