### ISSUE TITLE
Help - How is it supposed to fit together?

### ISSUE THREAD

**Issue by mariwing** [Odianosen25/Monitor-App#71]
Hi,

After reading your long and well-explained introduction to what Monitor-App can do, I really wanted to try it out. It seems like a very good approach to do pressence detection. But it seems like I am missing something obvious. If you could take a few minutes to explain it to me; it would be greatly appreciated.

I am running HASS.IO or what it is called these days. There is a container for AppDaemon that I have installed. I have used HACS to get your Monitor-App installed as well. I have configured this and it seems to be running just fine. 

I don't think HASS.IO have access to bluetooth hardware but that doesn't matter in my case since I would like to setup a few nodes around the house (Raspberry PI Zero). What am I supposed to install on those? The original monitor from Andrew or Monitor-App or AppDaemon and Monitor-App?

Because the script from @TheStigh doesn't work (not even after fixing the line endings), I installed the monitor from Andrew following the instructions on his git repo. That worked out fine and after configuring all the settings manually, it pushes messages to Home Assistants MQTT and they get proccesed by your Monitor-App and they show up as entities in Home Assistant 👍 

But as far as I can understand from your enthusiastic write-up I should be able to get the configuration from Monitor-App to propogate to all the nodes so I don't need to setup Andrews monitor manually. Is this correct?

If so; how am I supposed to do that (leading back to the question of what I should install on my nodes)? And last; what username/password am I supposed to use in the config in Monitor-App?

**Comment by Odianosen25** [comment]
> If you could take a few minutes to explain it to me; it would be greatly appreciated.

Yeah sure

> What am I supposed to install on those? The original monitor from Andrew or Monitor-App or AppDaemon and Monitor-App?

The original monitor script from Andrew, following the instructions on his GitHub page

> But as far as I can understand from your enthusiastic write-up I should be able to get the configuration from Monitor-App to propogate to all the nodes so I don't need to setup Andrews monitor manually. Is this correct?

Partially. The only configuration for now that is propagated to the other nodes, is the `known_devices`. I am supposed to work on an upgrade that propagates the rest, but haven't had the time to do it yet.

> And last; what username/password am I supposed to use in the config in Monitor-App?

The username/password you need there, are only those related to the nodes. If you want to reboot the hardware the nodes are running on, then you need to specify their username and passwords so the app can log into them.

Hope this helps, regards

**Comment by mariwing** [comment]
Thank you for the quick reply, this helped and clearified :-)
