### ISSUE TITLE
Entity presence.monitor_state not found in namespace mqtt

### ISSUE THREAD

**Issue by codeclinic** [Odianosen25/Monitor-App#9]
I'm seeing the following warning in my logs:

`Jan 10 14:59:27 HA-SERVER appdaemon[6112]: 2020-01-10 14:59:27.925970 INFO AppDaemon: Loading App Module: /home/appdaemon/.appdaemon/conf/apps/home_presence_app.py
Jan 10 14:59:27 HA-SERVER appdaemon[6112]: 2020-01-10 14:59:27.941633 INFO AppDaemon: Initializing app home_presence_app using class HomePresenceApp from module home_presence_app
**Jan 10 14:59:27 HA-SERVER appdaemon[6112]: 2020-01-10 14:59:27.967513 WARNING home_presence_app: home_presence_app: Entity presence.monitor_state not found in namespace mqtt**
Jan 10 14:59:27 HA-SERVER appdaemon[6112]: 2020-01-10 14:59:27.969570 INFO AppDaemon: home_presence_app: Entity presence.monitor_state created in namespace: mqtt
Jan 10 14:59:28 HA-SERVER appdaemon[6112]: 2020-01-10 14:59:28.022786 INFO AppDaemon: App initialization complete
`

Is this something that I should be concerned about?

**Comment by Odianosen25** [comment]
@codeclinic,

Apologies for just responding, but its nothing to be concerned about really. It should only show up once, and thats after AD restarts.

Regards
